site_name: HardenedNixOS Profile
site_description: Hardened NixOS with feature of Grescurity and aggressive security settings
site_url: https://hardenedlinux.github.io/HardenedNixOS-Profile
repo_name: hardenedlinux/HardenedNixOS-Profile
repo_url: https://github.com/hardenedlinux/HardenedNixOS-Profile

nav:
- Home Page: index.md

extra_css:
  - stylesheets/extra.css


theme: material

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
